name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build project
        run: bun run build
        env:
          NODE_ENV: production

      - name: Create Cloudflare Pages project if not exists
        run: |
          # Try to get the project first
          PROJECT_EXISTS=$(curl -s -X GET "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/${{ secrets.CLOUDFLARE_PROJECT_NAME }}" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" | jq -r '.success')
          
          if [ "$PROJECT_EXISTS" != "true" ]; then
            echo "Project doesn't exist, creating new Cloudflare Pages project..."
            curl -X POST "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects" \
              -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
              -H "Content-Type: application/json" \
              --data '{
                "name": "${{ secrets.CLOUDFLARE_PROJECT_NAME }}",
                "production_branch": "main"
              }'
            echo "Cloudflare Pages project created successfully"
          else
            echo "Project already exists, skipping creation"
          fi

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        id: cloudflare_pages_deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: dist
          wranglerVersion: '3'

      - name: Update repository website URL
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            const deploymentUrl = "${{ steps.cloudflare_pages_deploy.outputs.url }}";
            
            if (deploymentUrl) {
              try {
                await github.rest.repos.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  homepage: deploymentUrl,
                  description: context.payload.repository.description || "Educational platform for Massa blockchain development"
                });
                console.log(`Repository website URL updated to: ${deploymentUrl}`);
              } catch (error) {
                console.error('Failed to update repository website URL:', error);
                throw error;
              }
            }

      - name: Add PR comment with deployment URL
        if: github.event_name == 'pull_request' && steps.cloudflare_pages_deploy.outputs.url
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const deploymentUrl = "${{ steps.cloudflare_pages_deploy.outputs.url }}";
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Preview deployment is ready!**\n\n✅ Preview URL: ${deploymentUrl}\n\nThis deployment will be available until the PR is merged or closed.`
            });
